### ISSUE TITLE
Cannot change guideline color in v2.0.4

### ISSUE THREAD

**Issue by RobertBernstein** [pharring/EditorGuidelines#13] opened 2018-12-11 19:35 UTC
I upgraded to v2.0.4 and the Guideline color no longer appears under the Text Editor settings.  I am running VS 2017 version 15.9.3.

![image](https://user-images.githubusercontent.com/845559/49825213-e28efc80-fd51-11e8-98ee-8188898c74aa.png)

![image](https://user-images.githubusercontent.com/845559/49825221-e884dd80-fd51-11e8-8946-90c161ae2773.png)

![image](https://user-images.githubusercontent.com/845559/49825227-eb7fce00-fd51-11e8-9b78-31248b0aa312.png)

**Comment by pharring** [comment] 2018-12-11 21:46
Thanks for the report @RobertBernstein. I can't reproduce this myself. The Guidelines entry is there for me in 2.0.4 on Visual Studio 15.9.3.
Is anyone else seeing this problem?

**Comment by RobertBernstein** [comment] 2018-12-12 15:49
@pharring , I uninstalled and reinstalled the extension and then the Guideline option was available in Fonts and Colors again.  Unfortunately, I don't know why it disappeared in the first place.

**Comment by pharring** [comment] 2018-12-12 23:05
Thanks for replying, @RobertBernstein. Closing for now.

**Closed by pharring** 2018-12-12 23:05 UTC
Labels: bug

**Comment by RobertBernstein** [comment] 2018-12-13 01:14
You're welcome.
