### ISSUE TITLE
Extension stopped working after most recent Visual Studio 2022 update

### ISSUE THREAD

**Issue by riskcon** [pharring/EditorGuidelines#96] opened 2022-02-16 17:16 UTC
The Editor Guidelines extension does not work anymore since the most recent Visual Studio 2022 update.

```
The context menu entry is still there, but if I choose "Add Guideline" an error message occurs:

The 'EditorGuidelinesPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\RN\AppData\Roaming\Microsoft\VisualStudio\17.0_da57060b\ActivityLog.xml'.

Restarting Visual Studio could help resolve this issue.
```

Restarting VS or reinstalling the extension does not resolve the issue.

The mentioned activity log contains this entry:
  ```
<entry>
    <record>3133</record>
    <time>2022/02/16 17:14:11.945</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [EditorGuidelinesPackage]Source: &apos;EditorGuidelines&apos; Description: Could not load file or assembly &apos;Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos; or one of its dependencies. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;File name: &apos;Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos;&#x000D;&#x000A;   at EditorGuidelines.EditorGuidelinesPackage.&lt;InitializeAsync&gt;d__4.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at EditorGuidelines.EditorGuidelinesPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Protokollierung der Assemblybindung ist AUS.&#x000D;&#x000A;Sie k&#x00F6;nnen die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.&#x000D;&#x000A;Hinweis: Die Protokollierung der Assemblybindungsfehler f&#x00FC;hrt zu einer gewissen Leistungseinbu&#x00DF;e.&#x000D;&#x000A;Sie k&#x00F6;nnen dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.&#x000D;&#x000A;</description>
    <guid>{A0B80B01-BE16-4C42-AB44-7F8D057FAA2F}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>

```

### Solution

I had to install the Developer Analytic Tools - no idea if they were uninstalled during the update. I did not add/remove features of Visual Studio recently:
![image](https://user-images.githubusercontent.com/47387694/154320455-41e441a9-2337-4997-8ea1-86428fb6e7b2.png)

**Comment by pharring** [comment] 2022-02-16 18:31
A duplicate of #87
Looks like you found the correct workaround.

**Closed by pharring** 2022-02-16 18:31 UTC
Labels: duplicate

**Comment by pharring** [comment] 2022-02-28 19:20
> It might be good to put this on the Getting Started page

Done with https://github.com/pharring/EditorGuidelines/commit/236000d5d33627cab0465dad0cb46b7b4a132e3d
